name: Run Flask with Ngrok


on:
  push:
    branches: [ master ]

jobs:
  flask-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyngrok

      - name: Run Flask with Ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          nohup python app.py &
          sleep 5
          python -c "
from pyngrok import ngrok, conf
conf.get_default().auth_token = '${{ secrets.NGROK_AUTHTOKEN }}'
url = ngrok.connect(5000)
print(f'🔗 Flask доступний за адресою: {url}')
          "
