name: Flask with ngrok

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin

    - name: Authenticate ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Run Flask with ngrok
      env:
        FLASK_APP: app.py
      run: |
        nohup flask run --host=0.0.0.0 --port=5000 &
        sleep 5
        nohup ngrok http 5000 > ngrok.log &
        sleep 10
        echo "=== NGROK URL ==="
        curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
