name: Run Flask with Ngrok

on:
  push:
    branches: [ master ]

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flask ngrok

      - name: Run Flask + Ngrok
        run: |
          export FLASK_APP=app.py
          flask run --host=0.0.0.0 &
          sleep 5
          ngrok http 5000
